import { Game } from "./Configuration";

const defaultGames: Game[] = [
  {
    "name": "mycity",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "cty_board_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff"
  },
  {
    "name": "abyss",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-panel-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".desktop_version #centered-table { margin-left: 46px; }"
  },
  {
    "name": "conspiracy",
    "position": "bottom",
    "positionBottom": "140px",
    "left": "12px",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#ffffff",
    "css": ".show-playermat-button { visibility: hidden; }"
  },
  {
    "name": "thurnandtaxis",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "miniboard_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#thurntaxis_board, .desktop_version #page-title { margin-left: 55px; }"
  },
  {
    "name": "seasons",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "anchor_player_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version .tableau { margin-left: 46px; } .anchor-up { display: none; } .show-player-tableau { visibility: hidden; }"
  },
  {
    "name": "azul",
    "position": "bottom",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player-hand-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000"
  },
  {
    "name": "wingspan",
    "position": "auto",
    "positionTop": "150px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "aviary_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #wsp_opponent_board_area { padding-left: 40px; }"
  },
  {
    "name": "architectsofthewestkingdom",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "player{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-title { margin-left: 52px; } .desktop_version #pagesection_gameview { padding-left: 52px; }"
  },
  {
    "name": "amerigo",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "playersection_{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #page-title { margin-left: 50px; } #playersections { padding-left: 50px; }"
  },
  {
    "name": "agricola",
    "position": "auto",
    "positionTop": "150px",
    "positionBottom": "auto",
    "left": "6px",
    "playerPanel": "player-board-resizable-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #position-wrapper { padding-left: 52px; }"
  },
  {
    "name": "akropolis",
    "position": "top",
    "positionTop": "40vh",
    "left": "0.5em",
    "playerPanel": "player-table-{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": "#jump-controls { display: none; }"
  },
  {
    "name": "villagers",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "vil_village_{{player_id}}",
    "playerPanelOffset": 0,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #villages { margin-left: 50px; }"
  },
  {
    "name": "spots",
    "position": "auto",
    "positionTop": "75px",
    "positionBottom": "auto",
    "left": "0.5em",
    "playerPanel": "spt-cards{{player_id}}",
    "playerPanelOffset": 5,
    "iconBackground": "#ebd5bd",
    "iconBorder": "#222222",
    "iconColor": "#222222",
    "iconShadow": "#000000",
    "css": ".desktop_version #spt-gameArea{ margin-left: 25px; }"
  }
];

export default defaultGames;